# Generated by Django 2.2.6 on 2019-10-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_questions',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
