# Generated by Django 2.2.6 on 2019-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_auto_20191024_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='encerrada',
            field=models.BooleanField(default=False),
        ),
    ]
